Logger:
      log_file_name: logs
      log_location: Logs
DataPath: Data\PetImages\
BadDataPath: 
      root_folder: Data\BadData\
      BadDataFile: BadImg.txt
      cat: cat
      dog: dog
Model:
      Model_dir: Models
      baseModel_name: baseModel.h5
      TrainedModel_name: trained_model.h5



